stages:
  - release

release:
  stage: release
  image: curlimages/curl:latest
  dependencies:
    - build
  script:
    - echo "Extracting changelog..."
    - apk add --no-cache bash grep coreutils jq
    - awk '/^## \[/{if (p) exit; p=1} p' CHANGELOG.md > latest_changelog.md

    - echo "Uploading JAR file to GitLab..."
    - |
      UPLOAD_RESPONSE=$(curl --silent --request POST \
        --header "PRIVATE-TOKEN: $GITLAB_TOKEN" \
        --form "file=@target/connector-gitlab-rest-${CI_COMMIT_TAG#v}.jar" \
        "https://gitlab.com/api/v4/projects/$CI_PROJECT_ID/uploads")

    - FILE_URL=$(echo "$UPLOAD_RESPONSE" | jq -r .url)
    - echo "JAR uploaded to: $FILE_URL"

    - echo "Creating GitLab release for tag $CI_COMMIT_TAG"
    - |
      curl --request POST \
        --header "PRIVATE-TOKEN: $GITLAB_TOKEN" \
        --data "name=Release $CI_COMMIT_TAG" \
        --data-urlencode "tag_name=$CI_COMMIT_TAG" \
        --data-urlencode "description=$(cat latest_changelog.md)" \
        --data-urlencode "assets[links][][name]=Download JAR" \
        --data-urlencode "assets[links][][url]=$CI_PROJECT_URL$FILE_URL" \
        "https://gitlab.com/api/v4/projects/$CI_PROJECT_ID/releases"
  only:
    - tags